# Generated by Django 6.0.6 on 2026-09-12 18:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0009_tenantconfig_show_whatsapp_on_public_landing_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentAccessGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Está Activo?')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='¿Está Eliminado?')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Baja Lógica')),
                ('permission', models.CharField(help_text='Llave fina exacta del manifiesto; sin comodines.', max_length=100)),
                ('reason', models.TextField(help_text='Motivo de la autorización excepcional.')),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('granted_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='issued_department_grants', to=settings.AUTH_USER_MODEL)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='department_grants', to='security.userapprole')),
                ('source_department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_access_grants', to='security.dependencia')),
                ('target_department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_access_grants', to='security.dependencia')),
            ],
            options={
                'verbose_name': 'Autorización entre dependencias',
                'verbose_name_plural': 'Autorizaciones entre dependencias',
                'constraints': [models.UniqueConstraint(fields=('membership', 'source_department', 'target_department', 'permission'), name='uq_department_access_grant')],
            },
        ),
    ]
