# Generated by Django 6.0.6 on 2026-09-12 18:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0010_department_access_grants'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verification_sent_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verification_nonce',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='user',
            name='session_version',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
