# Generated by Django 6.0.6 on 2026-09-12 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0012_account_sessions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_manager',
            field=models.BooleanField(default=False, help_text='Administrador técnico de Seguridad y Configuración; otros módulos requieren membresía y permisos.'),
        ),
    ]
