# Generated by Django 6.0.6 on 2026-09-13 00:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0013_technical_authority'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityauditlog',
            name='correlation_id',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='securityauditlog',
            name='system_actor',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='securityauditlog',
            name='operator_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='logs', to=settings.AUTH_USER_MODEL, verbose_name='Operador'),
        ),
    ]
