# Generated by Django 6.0.6 on 2026-09-14 20:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0014_audit_correlation_system_actor'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pending_email',
            field=models.EmailField(blank=True, default='', editable=False, max_length=254),
        ),
        migrations.AddField(
            model_name='user',
            name='pending_email_nonce',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='user',
            name='pending_email_requested_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
