# Generated by Django 6.0.6 on 2026-09-16 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0015_user_pending_email_user_pending_email_nonce_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantconfig',
            name='aviso_privacidad',
            field=models.TextField(blank=True, default='', help_text='Texto legal del aviso de privacidad institucional, visible en el portal público.', verbose_name='Aviso de Privacidad'),
        ),
        migrations.AddField(
            model_name='tenantconfig',
            name='politica_cookies',
            field=models.TextField(blank=True, default='', help_text='Texto legal de la política de cookies institucional, visible en el portal público.', verbose_name='Política de Cookies'),
        ),
    ]
