# Generated by Django 6.0.6 on 2026-09-23 19:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0016_agrega_privacidad_y_cookies_tenant_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantconfig',
            name='accent_color',
            field=models.CharField(default='#059669', help_text='Color de acento de marca institucional en formato hexadecimal, ej. #059669.', max_length=7, validators=[django.core.validators.RegexValidator(message='El color debe ser un valor hexadecimal válido, por ejemplo #0B1A15.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Color de Acento (HEX)'),
        ),
        migrations.AlterField(
            model_name='tenantconfig',
            name='primary_color',
            field=models.CharField(default='#0B1A15', help_text='Color primario de marca institucional en formato hexadecimal, ej. #0B1A15.', max_length=7, validators=[django.core.validators.RegexValidator(message='El color debe ser un valor hexadecimal válido, por ejemplo #0B1A15.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Color Primario (HEX)'),
        ),
        migrations.AlterField(
            model_name='tenantconfig',
            name='secondary_color',
            field=models.CharField(default='#475467', help_text='Color secundario de marca institucional en formato hexadecimal, ej. #475467.', max_length=7, validators=[django.core.validators.RegexValidator(message='El color debe ser un valor hexadecimal válido, por ejemplo #0B1A15.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Color Secundario (HEX)'),
        ),
    ]
