# Generated by Django 6.0.6 on 2026-09-25 18:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Linea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Eliminado')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('identificador', models.CharField(help_text='Número telefónico o identificador del enlace (p. ej. C1G-2204-0353).', max_length=60, verbose_name='Número o circuito')),
                ('identificador_normalizado', models.CharField(editable=False, max_length=60, unique=True)),
                ('sitio', models.CharField(max_length=150, verbose_name='Sitio')),
                ('municipio', models.CharField(default='Coatzacoalcos', max_length=100, verbose_name='Municipio')),
                ('direccion', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
                ('tipo', models.CharField(choices=[('telefono', 'Línea telefónica'), ('internet', 'Internet'), ('enlace', 'Enlace dedicado'), ('otro', 'Otro')], default='telefono', max_length=10, verbose_name='Tipo')),
                ('velocidad', models.CharField(blank=True, help_text='Ej. 300 Mb simétrico.', max_length=80, verbose_name='Paquete o velocidad')),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitud')),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitud')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
            ],
            options={
                'verbose_name': 'Línea',
                'verbose_name_plural': 'Líneas',
                'db_table': 'tel_linea',
                'ordering': ['sitio', 'identificador'],
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Eliminado')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('linea_texto', models.CharField(editable=False, max_length=60)),
                ('sitio_texto', models.CharField(editable=False, max_length=150)),
                ('folio', models.CharField(max_length=40, verbose_name='Folio de Telmex')),
                ('folio_normalizado', models.CharField(editable=False, max_length=40, unique=True)),
                ('estatus', models.CharField(choices=[('pendiente', 'Pendiente'), ('atendido', 'Atendido'), ('cancelado', 'Cancelado')], db_index=True, default='pendiente', max_length=10, verbose_name='Estatus')),
                ('levantado', models.DateField(verbose_name='Levantado')),
                ('atendido', models.DateField(blank=True, null=True, verbose_name='Atendido')),
                ('detalle', models.TextField(blank=True, verbose_name='Detalle de la falla')),
                ('contacto_nombre', models.CharField(max_length=150, verbose_name='Contacto en sitio')),
                ('contacto_telefono', models.CharField(max_length=30, verbose_name='Teléfono del contacto')),
                ('responsable_nombre', models.CharField(blank=True, editable=False, max_length=200)),
                ('motivo_cancelacion', models.TextField(blank=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('linea', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reportes', to='telefonia.linea', verbose_name='Línea')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Responsable de Innovación')),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
                'db_table': 'tel_reporte',
                'ordering': ['-levantado', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('creado', 'Reporte levantado'), ('comentario', 'Comentario'), ('evidencia', 'Evidencia'), ('atendido', 'Marcado como atendido'), ('cancelado', 'Cancelado'), ('reabierto', 'Reabierto'), ('editado', 'Datos corregidos'), ('responsable', 'Responsable')], max_length=12)),
                ('usuario_nombre', models.CharField(blank=True, max_length=200)),
                ('texto', models.TextField(blank=True)),
                ('datos', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='telefonia.reporte')),
            ],
            options={
                'db_table': 'tel_movimiento',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Eliminado')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('tipo', models.CharField(choices=[('foto', 'Foto'), ('velocidad', 'Prueba de velocidad'), ('otra', 'Otra')], default='foto', max_length=10)),
                ('ruta', models.CharField(editable=False, max_length=300)),
                ('nombre_original', models.CharField(max_length=200)),
                ('content_type', models.CharField(max_length=60)),
                ('tamano', models.PositiveIntegerField()),
                ('sha256', models.CharField(db_index=True, editable=False, max_length=64)),
                ('subido_por_nombre', models.CharField(blank=True, max_length=200)),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidencias', to='telefonia.reporte')),
            ],
            options={
                'db_table': 'tel_evidencia',
                'ordering': ['created_at'],
            },
        ),
    ]
