# Generated by Django 6.0.6 on 2026-09-26 04:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('nombre', models.CharField(max_length=200, verbose_name='Evento')),
                ('lugar', models.CharField(max_length=200, verbose_name='Lugar')),
                ('inicio', models.DateTimeField(db_index=True, verbose_name='Inicio')),
                ('fin', models.DateTimeField(verbose_name='Fin')),
                ('descripcion', models.TextField(blank=True, verbose_name='Qué se cubre')),
                ('ticket', models.CharField(blank=True, help_text='Folio del ticket del que nació el evento, si lo hay.', max_length=60, verbose_name='Ticket')),
                ('estatus', models.CharField(choices=[('programado', 'Programado'), ('en_curso', 'En curso'), ('concluido', 'Concluido'), ('cancelado', 'Cancelado')], db_index=True, default='programado', max_length=12, verbose_name='Estado')),
                ('motivo_cancelacion', models.TextField(blank=True, verbose_name='Motivo de cancelación')),
                ('notas_cierre', models.TextField(blank=True, verbose_name='Notas de cierre')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'evt_evento',
                'ordering': ['inicio'],
            },
        ),
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('usuario_nombre', models.CharField(blank=True, max_length=200)),
                ('accion', models.CharField(db_index=True, max_length=30)),
                ('detalle', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bitacora', to='eventos.evento')),
            ],
            options={
                'db_table': 'evt_bitacora',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('tecnico_nombre', models.CharField(max_length=200)),
                ('desde', models.DateTimeField(verbose_name='Desde')),
                ('hasta', models.DateTimeField(verbose_name='Hasta')),
                ('nota', models.CharField(blank=True, max_length=200, verbose_name='Nota')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='eventos.evento')),
            ],
            options={
                'db_table': 'evt_asignacion',
                'ordering': ['desde', 'tecnico_nombre'],
            },
        ),
        migrations.CreateModel(
            name='TramiteLinea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('tipo', models.CharField(choices=[('reubicacion', 'Reubicar una línea'), ('nueva', 'Contratar línea nueva'), ('otro', 'Otro')], default='reubicacion', max_length=12, verbose_name='Trámite')),
                ('descripcion', models.CharField(max_length=250, verbose_name='Descripción')),
                ('referencia', models.CharField(blank=True, max_length=120, verbose_name='Línea o enlace')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_tramite', 'En trámite'), ('listo', 'Listo')], default='pendiente', max_length=12, verbose_name='Estado')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tramites', to='eventos.evento')),
            ],
            options={
                'db_table': 'evt_tramite_linea',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ValeSalida',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('referencia', models.CharField(max_length=80, verbose_name='Vale (número o UUID)')),
                ('nota', models.CharField(blank=True, max_length=200, verbose_name='Qué se lleva')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vales', to='eventos.evento')),
            ],
            options={
                'db_table': 'evt_vale',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='evento',
            constraint=models.CheckConstraint(condition=models.Q(('fin__gt', models.F('inicio'))), name='evt_evento_fin_despues_de_inicio'),
        ),
        migrations.AddConstraint(
            model_name='asignacion',
            constraint=models.CheckConstraint(condition=models.Q(('hasta__gt', models.F('desde'))), name='evt_asignacion_hasta_despues_de_desde'),
        ),
        migrations.AddConstraint(
            model_name='valesalida',
            constraint=models.UniqueConstraint(fields=('evento', 'referencia'), name='evt_vale_unico_por_evento'),
        ),
    ]
