# Generated by Django 6.0.6 on 2026-09-26 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='valesalida',
            name='etiqueta',
            field=models.CharField(blank=True, max_length=200, verbose_name='Vale (texto al vincular)'),
        ),
        migrations.AddField(
            model_name='valesalida',
            name='ref_id',
            field=models.UUIDField(blank=True, help_text='UUID del vale cuando se eligió del satélite de préstamos.', null=True, verbose_name='Vale elegido del sistema'),
        ),
    ]
