# Generated by Django 6.0.6 on 2026-09-26 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_valesalida_etiqueta_valesalida_ref_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramitelinea',
            name='etiqueta',
            field=models.CharField(blank=True, max_length=200, verbose_name='Línea (texto al vincular)'),
        ),
        migrations.AddField(
            model_name='tramitelinea',
            name='ref_id',
            field=models.UUIDField(blank=True, help_text='UUID de la línea cuando se eligió del satélite de telefonía.', null=True, verbose_name='Línea elegida del sistema'),
        ),
    ]
