# Generated by Django 6.0.6 on 2026-09-26 04:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_economicos_p1', models.PositiveSmallIntegerField(default=1, verbose_name='Días económicos del 1.er periodo (enero a junio)')),
                ('dias_economicos_p2', models.PositiveSmallIntegerField(default=1, verbose_name='Días económicos del 2.º periodo (julio a diciembre)')),
            ],
            options={
                'verbose_name': 'Configuración',
                'db_table': 'perm_configuracion',
            },
        ),
        migrations.CreateModel(
            name='UmbralSede',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('sede_uuid', models.UUIDField(unique=True, verbose_name='Sede del Core')),
                ('sede_nombre', models.CharField(max_length=150, verbose_name='Sede')),
                ('minimo', models.PositiveSmallIntegerField(default=1, verbose_name='Mínimo de personal presente')),
            ],
            options={
                'db_table': 'perm_umbral_sede',
                'ordering': ['sede_nombre'],
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('tipo', models.CharField(choices=[('sindicalizado', 'Sindicalizado'), ('confianza', 'Confianza')], default='confianza', max_length=15, verbose_name='Tipo de personal')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de ingreso')),
                ('sede_uuid', models.UUIDField(blank=True, db_index=True, null=True, verbose_name='Sede del Core')),
                ('sede_nombre', models.CharField(blank=True, max_length=150, verbose_name='Sede')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='empleado_permisos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'perm_empleado',
                'ordering': ['usuario__first_name', 'usuario__last_name'],
            },
        ),
        migrations.CreateModel(
            name='RangoAntiguedad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('tipo', models.CharField(choices=[('sindicalizado', 'Sindicalizado'), ('confianza', 'Confianza')], max_length=15, verbose_name='Tipo de personal')),
                ('desde_anios', models.PositiveSmallIntegerField(verbose_name='Desde (años de antigüedad)')),
                ('dias_p1', models.PositiveSmallIntegerField(verbose_name='Días del 1.er periodo')),
                ('dias_p2', models.PositiveSmallIntegerField(verbose_name='Días del 2.º periodo')),
            ],
            options={
                'db_table': 'perm_rango_antiguedad',
                'ordering': ['tipo', 'desde_anios'],
                'constraints': [models.UniqueConstraint(fields=('tipo', 'desde_anios'), name='perm_rango_unico')],
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('tipo', models.CharField(choices=[('vacaciones', 'Vacaciones'), ('economico', 'Día económico')], max_length=12, verbose_name='Tipo')),
                ('anio', models.PositiveSmallIntegerField(verbose_name='Año')),
                ('periodo', models.PositiveSmallIntegerField(choices=[(1, '1.er periodo'), (2, '2.º periodo')], verbose_name='Periodo')),
                ('fecha_inicio', models.DateField(verbose_name='Del')),
                ('fecha_fin', models.DateField(verbose_name='Al')),
                ('dias', models.PositiveSmallIntegerField(verbose_name='Días que descuenta')),
                ('comentarios', models.TextField(blank=True, verbose_name='Comentarios')),
                ('estatus', models.CharField(choices=[('activa', 'Activa'), ('cancelada', 'Cancelada')], db_index=True, default='activa', max_length=10, verbose_name='Estatus')),
                ('motivo_cancelacion', models.TextField(blank=True)),
                ('validado', models.BooleanField(db_index=True, default=False, verbose_name='Validado')),
                ('validado_en', models.DateTimeField(blank=True, null=True)),
                ('sede_uuid', models.UUIDField(blank=True, null=True)),
                ('sede_nombre', models.CharField(blank=True, max_length=150)),
                ('bajo_umbral', models.JSONField(blank=True, default=list, verbose_name='Días bajo el mínimo de la sede')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to='permisos_personal.empleado')),
                ('validado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'perm_solicitud',
                'ordering': ['-fecha_inicio', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accion', models.CharField(max_length=20)),
                ('usuario_nombre', models.CharField(blank=True, max_length=200)),
                ('texto', models.TextField(blank=True)),
                ('datos', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='permisos_personal.empleado')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('solicitud', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='permisos_personal.solicitud')),
            ],
            options={
                'db_table': 'perm_movimiento',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AjusteDias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('anio', models.PositiveSmallIntegerField(verbose_name='Año')),
                ('periodo', models.PositiveSmallIntegerField(choices=[(1, '1.er periodo'), (2, '2.º periodo')], verbose_name='Periodo')),
                ('dias', models.PositiveSmallIntegerField(verbose_name='Días')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ajustes', to='permisos_personal.empleado')),
            ],
            options={
                'db_table': 'perm_ajuste_dias',
                'constraints': [models.UniqueConstraint(fields=('empleado', 'anio', 'periodo'), name='perm_ajuste_unico')],
            },
        ),
        migrations.AddConstraint(
            model_name='solicitud',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_fin__gte', models.F('fecha_inicio'))), name='perm_fechas_validas'),
        ),
    ]
