# Generated by Django 6.0.6 on 2026-09-24 17:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Eliminado')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('dependencia_uuid', models.UUIDField(blank=True, db_index=True, help_text='UUID de la dependencia del Core que define quién ve estos oficios.', null=True, verbose_name='Dependencia del Core')),
            ],
            options={
                'verbose_name': 'Dirección',
                'verbose_name_plural': 'Direcciones',
                'db_table': 'oficios_direccion',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Eliminado')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('sentido', models.CharField(choices=[('recibido', 'Recibido'), ('enviado', 'Enviado')], max_length=10, verbose_name='Sentido')),
                ('clase', models.CharField(choices=[('oficio', 'Oficio'), ('vale_prestamo', 'Vale de préstamo'), ('diagnostico_tecnico', 'Diagnóstico técnico'), ('dictamen_alta', 'Dictamen de alta'), ('dictamen_baja', 'Dictamen de baja'), ('comunicado', 'Comunicado'), ('otro', 'Otro')], default='oficio', max_length=25, verbose_name='Clase de documento')),
                ('direccion_nombre', models.CharField(max_length=150, verbose_name='Dirección (al registrar)')),
                ('contraparte', models.CharField(help_text='Quién envía (recibidos) o a quién se dirige (enviados).', max_length=200, verbose_name='Remitente o destinatario')),
                ('director_nombre', models.CharField(blank=True, max_length=200, verbose_name='Director (al registrar)')),
                ('asunto', models.CharField(max_length=300, verbose_name='Asunto')),
                ('fecha', models.DateField(verbose_name='Fecha del documento')),
                ('folio', models.CharField(blank=True, db_index=True, max_length=80, verbose_name='Folio')),
                ('anio', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('consecutivo', models.PositiveIntegerField(blank=True, null=True)),
                ('archivo_hash', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='SHA-256')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('direccion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='seguimientos_oficios.direccion', verbose_name='Dirección')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'db_table': 'oficios_documento',
                'ordering': ['-fecha', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistorialDocumento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accion', models.CharField(choices=[('creado', 'Creado'), ('editado', 'Editado'), ('eliminado', 'Eliminado')], max_length=12)),
                ('usuario_nombre', models.CharField(blank=True, max_length=200)),
                ('datos', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial', to='seguimientos_oficios.documento')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'oficios_historial',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Nomenclatura',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Eliminado')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('clase', models.CharField(choices=[('oficio', 'Oficio'), ('vale_prestamo', 'Vale de préstamo'), ('diagnostico_tecnico', 'Diagnóstico técnico'), ('dictamen_alta', 'Dictamen de alta'), ('dictamen_baja', 'Dictamen de baja'), ('comunicado', 'Comunicado'), ('otro', 'Otro')], max_length=25, verbose_name='Clase de documento')),
                ('plantilla', models.CharField(default='{n:03d}/{anio}', help_text='Ej. IN-{n:03d}/{anio} da IN-001/2026. Tokens: {n}, {n:03d} y {anio}.', max_length=60, verbose_name='Plantilla')),
                ('direccion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nomenclaturas', to='seguimientos_oficios.direccion')),
            ],
            options={
                'verbose_name': 'Nomenclatura',
                'verbose_name_plural': 'Nomenclaturas',
                'db_table': 'oficios_nomenclatura',
                'ordering': ['direccion__nombre', 'clase'],
            },
        ),
        migrations.CreateModel(
            name='ConsecutivoFolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveSmallIntegerField(verbose_name='Año')),
                ('ultimo', models.PositiveIntegerField(default=0, verbose_name='Último número')),
                ('nomenclatura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consecutivos', to='seguimientos_oficios.nomenclatura')),
            ],
            options={
                'db_table': 'oficios_consecutivo',
            },
        ),
        migrations.AddConstraint(
            model_name='documento',
            constraint=models.UniqueConstraint(condition=models.Q(('sentido', 'enviado')), fields=('direccion', 'folio'), name='oficios_folio_enviado_unico'),
        ),
        migrations.AddConstraint(
            model_name='nomenclatura',
            constraint=models.UniqueConstraint(fields=('direccion', 'clase'), name='oficios_nomenclatura_unica'),
        ),
        migrations.AddConstraint(
            model_name='consecutivofolio',
            constraint=models.UniqueConstraint(fields=('nomenclatura', 'anio'), name='oficios_consecutivo_unico'),
        ),
    ]
