# Generated by Django 6.0.6 on 2026-09-24 17:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Eliminado')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('dependencia_uuid', models.UUIDField(blank=True, db_index=True, help_text='UUID de la dependencia del Core que define quién ve estos oficios.', null=True, verbose_name='Dependencia del Core')),
            ],
            options={
                'verbose_name': 'Dirección',
                'verbose_name_plural': 'Direcciones',
                'db_table': 'oficios_direccion',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Eliminado')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('tipo', models.CharField(choices=[('recibido', 'Recibido'), ('enviado', 'Enviado')], max_length=10, verbose_name='Tipo')),
                ('contraparte', models.CharField(help_text='Quién envía (recibidos) o a quién se dirige (enviados).', max_length=200, verbose_name='Remitente o destinatario')),
                ('director', models.CharField(blank=True, max_length=200, verbose_name='Director')),
                ('asunto', models.CharField(max_length=300, verbose_name='Asunto')),
                ('fecha', models.DateField(verbose_name='Fecha del oficio')),
                ('folio', models.CharField(blank=True, db_index=True, max_length=80, verbose_name='Folio')),
                ('archivo_hash', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='SHA-256')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('direccion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='seguimientos_oficios.direccion', verbose_name='Dirección')),
            ],
            options={
                'verbose_name': 'Oficio',
                'verbose_name_plural': 'Oficios',
                'db_table': 'oficios_documento',
                'ordering': ['-fecha', '-created_at'],
            },
        ),
    ]
