# Generated by Django 6.0.6 on 2026-09-24 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimientos_oficios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='estado',
            field=models.CharField(choices=[('registrado', 'Registrado'), ('generado', 'Generado'), ('entregado', 'Entregado'), ('concluido', 'Concluido'), ('cancelado', 'Cancelado')], db_index=True, default='generado', max_length=12, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='documento',
            name='fecha_entrega',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de entrega'),
        ),
        migrations.AddField(
            model_name='documento',
            name='motivo_cancelacion',
            field=models.TextField(blank=True, verbose_name='Motivo de cancelación'),
        ),
        migrations.AddField(
            model_name='documento',
            name='receptor_entrega',
            field=models.CharField(blank=True, max_length=200, verbose_name='Recibió la entrega'),
        ),
    ]
