# Generated by Django 6.0.6 on 2026-09-24 18:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimientos_oficios', '0002_estados_y_cancelacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='archivo_hash',
        ),
        migrations.AlterField(
            model_name='historialdocumento',
            name='accion',
            field=models.CharField(choices=[('creado', 'Creado'), ('editado', 'Editado'), ('adjuntado', 'Adjunto agregado'), ('eliminado', 'Eliminado')], max_length=12),
        ),
        migrations.CreateModel(
            name='Adjunto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rol', models.CharField(choices=[('original', 'Original escaneado'), ('evidencia', 'Evidencia de entrega')], max_length=10)),
                ('ruta', models.CharField(max_length=255, verbose_name='Ruta en el almacén')),
                ('nombre_original', models.CharField(max_length=255)),
                ('sha256', models.CharField(db_index=True, max_length=64, verbose_name='SHA-256')),
                ('tamano', models.PositiveBigIntegerField(verbose_name='Tamaño (bytes)')),
                ('subido_por_nombre', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjuntos', to='seguimientos_oficios.documento')),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'oficios_adjunto',
                'ordering': ['created_at'],
            },
        ),
    ]
