# Generated by Django 6.0.6 on 2026-09-24 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimientos_oficios', '0003_adjuntos'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdjuntoOCR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('listo', 'Listo'), ('error', 'Error')], db_index=True, default='pendiente', max_length=12)),
                ('texto', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
                ('intentos', models.PositiveSmallIntegerField(default=0)),
                ('iniciado_en', models.DateTimeField(blank=True, null=True)),
                ('terminado_en', models.DateTimeField(blank=True, null=True)),
                ('adjunto', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='ocr', to='seguimientos_oficios.adjunto')),
            ],
            options={
                'db_table': 'oficios_adjunto_ocr',
            },
        ),
    ]
