# Generated by Django 6.0.6 on 2026-09-24 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimientos_oficios', '0005_indice_busqueda_ocr'),
    ]

    operations = [
        migrations.AddField(
            model_name='direccion',
            name='ruta_evidencias',
            field=models.CharField(blank=True, help_text='Ruta relativa a la raíz de la bandeja donde se escanean las evidencias de entrega.', max_length=255, verbose_name='Carpeta de evidencias'),
        ),
        migrations.AddField(
            model_name='direccion',
            name='ruta_recibidos',
            field=models.CharField(blank=True, help_text='Ruta relativa a la raíz de la bandeja donde se escanean los oficios recibidos.', max_length=255, verbose_name='Carpeta de recibidos'),
        ),
    ]
