# Generated by Django 6.0.6 on 2026-09-24 19:08

from django.db import migrations, models
from django.utils.text import slugify


def llenar_slugs(apps, schema_editor):
    Direccion = apps.get_model("seguimientos_oficios", "Direccion")
    usados = set()
    for direccion in Direccion.objects.filter(slug__isnull=True).order_by("created_at"):
        base = slugify(direccion.nombre) or "direccion"
        candidato, n = base, 2
        while candidato in usados or Direccion.objects.filter(slug=candidato).exists():
            candidato, n = f"{base}-{n}", n + 1
        usados.add(candidato)
        Direccion.objects.filter(pk=direccion.pk).update(slug=candidato)



class Migration(migrations.Migration):

    dependencies = [
        ('seguimientos_oficios', '0006_rutas_bandeja'),
    ]

    operations = [
        migrations.AddField(
            model_name='direccion',
            name='slug',
            field=models.SlugField(editable=False, help_text='Nombre de carpeta en el almacén; se fija al crear la dirección y no cambia si se renombra.', max_length=160, null=True, unique=True, verbose_name='Carpeta de archivos'),
        ),
        migrations.RunPython(llenar_slugs, migrations.RunPython.noop),
    ]
