# Generated by Django 6.0.6 on 2026-09-24 20:58

from django.contrib.postgres.indexes import GinIndex
from django.contrib.postgres.search import SearchVector
from django.db import migrations, models

from satelites.seguimientos_oficios.textos import normalizar

INDICE_VIEJO = GinIndex(SearchVector("texto", config="spanish"), name="oficios_ocr_fts_idx")
INDICE_NUEVO = GinIndex(SearchVector("texto_normalizado", config="spanish"), name="oficios_ocr_fts2_idx")


def rellenar(apps, schema_editor):
    Documento = apps.get_model("seguimientos_oficios", "Documento")
    OCR = apps.get_model("seguimientos_oficios", "AdjuntoOCR")
    for documento in Documento.objects.all().iterator():
        documento.busqueda = normalizar(" ".join((documento.folio, documento.asunto, documento.contraparte, documento.director_nombre)))
        documento.save(update_fields=["busqueda"])
    for ocr in OCR.objects.exclude(texto="").iterator():
        ocr.texto_normalizado = normalizar(ocr.texto)
        ocr.save(update_fields=["texto_normalizado"])


def indice_adelante(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        modelo = apps.get_model("seguimientos_oficios", "AdjuntoOCR")
        schema_editor.remove_index(modelo, INDICE_VIEJO)
        schema_editor.add_index(modelo, INDICE_NUEVO)


def indice_atras(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        modelo = apps.get_model("seguimientos_oficios", "AdjuntoOCR")
        schema_editor.remove_index(modelo, INDICE_NUEVO)
        schema_editor.add_index(modelo, INDICE_VIEJO)



class Migration(migrations.Migration):

    dependencies = [
        ('seguimientos_oficios', '0009_gestor_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjuntoocr',
            name='texto_normalizado',
            field=models.TextField(blank=True, default='', editable=False),
        ),
        migrations.AddField(
            model_name='documento',
            name='busqueda',
            field=models.TextField(blank=True, default='', editable=False),
        ),
        migrations.RunPython(rellenar, migrations.RunPython.noop),
        migrations.RunPython(indice_adelante, indice_atras),
    ]
