# Generated by Django 6.0.6 on 2026-09-24 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimientos_oficios', '0010_busqueda_normalizada'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='contraparte_dependencia_uuid',
            field=models.UUIDField(blank=True, editable=False, help_text='UUID de la dependencia del Core cuando la contraparte es una dirección de la institución.', null=True, verbose_name='Dependencia remitente o destinataria'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='contraparte',
            field=models.CharField(help_text='Nombre de quien envía (recibidos) o a quién se dirige (enviados).', max_length=200, verbose_name='Remitente o destinatario'),
        ),
    ]
