# Generated by Django 6.0.6 on 2026-09-24 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimientos_oficios', '0011_contraparte_dependencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='direccion',
            name='ruta_firmados',
            field=models.CharField(blank=True, help_text='Ruta relativa a la raíz de la bandeja donde se escanean los oficios enviados ya firmados.', max_length=255, verbose_name='Carpeta de firmados'),
        ),
        migrations.AlterField(
            model_name='adjunto',
            name='rol',
            field=models.CharField(choices=[('original', 'Original escaneado'), ('firmado', 'Documento firmado'), ('evidencia', 'Evidencia de entrega')], max_length=10),
        ),
    ]
