# Generated by Django 6.0.6 on 2026-09-24 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimientos_oficios', '0012_documento_firmado'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjunto',
            name='eliminado',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='adjunto',
            name='eliminado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adjunto',
            name='eliminado_motivo',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='adjunto',
            name='eliminado_por_nombre',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='historialdocumento',
            name='accion',
            field=models.CharField(choices=[('creado', 'Creado'), ('editado', 'Editado'), ('adjuntado', 'Adjunto agregado'), ('quitado', 'Archivo quitado'), ('eliminado', 'Eliminado')], max_length=12),
        ),
    ]
