# Generated by Django 6.0.6 on 2026-09-24 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimientos_oficios', '0013_adjuntos_quitados'),
    ]

    operations = [
        migrations.AddField(
            model_name='direccion',
            name='folio_manual',
            field=models.BooleanField(default=True, help_text='Activo: quien registra un oficio enviado escribe su folio. Inactivo: se genera con la nomenclatura.', verbose_name='Folio manual'),
        ),
        migrations.AddField(
            model_name='documento',
            name='folio_manual',
            field=models.BooleanField(default=False, verbose_name='Folio capturado a mano'),
        ),
    ]
