# Generated by Django 6.0.6 on 2026-09-24 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimientos_oficios', '0014_folio_manual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='ruta_evidencias',
            field=models.CharField(blank=True, help_text='Carpeta donde se escanean las evidencias de entrega.', max_length=255, verbose_name='Carpeta de evidencias'),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='ruta_firmados',
            field=models.CharField(blank=True, help_text='Carpeta donde se escanean los oficios enviados ya firmados.', max_length=255, verbose_name='Carpeta de firmados'),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='ruta_recibidos',
            field=models.CharField(blank=True, help_text='Carpeta donde se escanean los oficios recibidos (ej. innovacion/oficios/recibidos).', max_length=255, verbose_name='Carpeta de recibidos'),
        ),
    ]
