# Generated by Django 6.0.6 on 2026-09-25 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seguimientos_oficios', '0015_textos_bandeja'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direccion',
            name='ruta_evidencias',
        ),
        migrations.RemoveField(
            model_name='direccion',
            name='ruta_firmados',
        ),
        migrations.RemoveField(
            model_name='direccion',
            name='ruta_recibidos',
        ),
    ]
