# Generated by Django 6.0.6 on 2026-09-25 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seguimientos_oficios', '0016_quitar_bandeja'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='gestor',
            name='oficios_gestor_usuario_unico',
        ),
        migrations.RemoveField(
            model_name='gestor',
            name='usuario',
        ),
    ]
