# Generated by Django 6.0.6 on 2026-09-25 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimientos_oficios', '0018_ocr_solo_recibidos_y_firmados'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjuntoocr',
            name='ruta_buscable',
            field=models.CharField(blank=True, help_text='PDF con el texto reconocido, solo para el visor; el original no se modifica.', max_length=255, verbose_name='Copia con capa de texto'),
        ),
    ]
