# Generated by Django 6.0.6 on 2026-09-25 02:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimientos_oficios', '0020_copias_en_carpeta_ocr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Eliminado')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('direccion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categorias', to='seguimientos_oficios.direccion')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'oficios_categoria',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='documento',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='seguimientos_oficios.categoria', verbose_name='Categoría'),
        ),
        migrations.AddConstraint(
            model_name='categoria',
            constraint=models.UniqueConstraint(fields=('direccion', 'nombre'), name='oficios_categoria_unica'),
        ),
    ]
