# Generated by Django 6.0.6 on 2026-09-25 04:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimientos_oficios', '0021_categorias'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gestor',
            name='usuario',
            field=models.ForeignKey(blank=True, help_text='Si el gestor tiene cuenta, entra desde el celular a sus pendientes.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddConstraint(
            model_name='gestor',
            constraint=models.UniqueConstraint(condition=models.Q(('usuario__isnull', False)), fields=('direccion', 'usuario'), name='oficios_gestor_usuario_unico'),
        ),
    ]
