# Generated by Django 6.0.6 on 2026-09-25 05:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimientos_oficios', '0022_gestor_usuario_movil'),
    ]

    operations = [
        migrations.AddField(
            model_name='direccion',
            name='vales_habilitados',
            field=models.BooleanField(default=False, help_text='Activo: la dirección presta bienes con vale (catálogo de bienes y seguimiento de préstamos).', verbose_name='Vales de préstamo'),
        ),
        migrations.AlterField(
            model_name='historialdocumento',
            name='accion',
            field=models.CharField(choices=[('creado', 'Creado'), ('editado', 'Editado'), ('adjuntado', 'Adjunto agregado'), ('prestamo', 'Préstamo'), ('quitado', 'Archivo quitado'), ('eliminado', 'Eliminado')], max_length=12),
        ),
        migrations.CreateModel(
            name='Bien',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Eliminado')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('nombre', models.CharField(max_length=150, verbose_name='Bien')),
                ('identificador', models.CharField(blank=True, max_length=120, verbose_name='Número de serie o etiqueta')),
                ('folio_inventario', models.CharField(blank=True, max_length=60, verbose_name='Folio de inventario')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('en_reparacion', 'En reparación'), ('baja', 'Baja')], db_index=True, default='disponible', max_length=15, verbose_name='Estado')),
                ('direccion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bienes', to='seguimientos_oficios.direccion')),
            ],
            options={
                'verbose_name': 'Bien',
                'verbose_name_plural': 'Bienes',
                'db_table': 'oficios_bien',
                'ordering': ['nombre', 'identificador'],
            },
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Eliminado')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('fecha_entrega', models.DateField(verbose_name='Fecha de entrega')),
                ('fecha_limite', models.DateField(verbose_name='Devolución límite')),
                ('fecha_devolucion', models.DateField(blank=True, null=True, verbose_name='Devuelto el')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('observaciones_devolucion', models.TextField(blank=True, verbose_name='Observaciones de la devolución')),
                ('documento', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='prestamo', to='seguimientos_oficios.documento')),
            ],
            options={
                'db_table': 'oficios_prestamo',
                'ordering': ['-fecha_entrega'],
            },
        ),
        migrations.CreateModel(
            name='PrestamoBien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abierto', models.BooleanField(db_index=True, default=True)),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='seguimientos_oficios.bien')),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='renglones', to='seguimientos_oficios.prestamo')),
            ],
            options={
                'db_table': 'oficios_prestamo_bien',
            },
        ),
        migrations.AddConstraint(
            model_name='bien',
            constraint=models.UniqueConstraint(condition=models.Q(('folio_inventario', ''), _negated=True), fields=('direccion', 'folio_inventario'), name='oficios_bien_folio_inventario_unico'),
        ),
        migrations.AddConstraint(
            model_name='prestamobien',
            constraint=models.UniqueConstraint(fields=('prestamo', 'bien'), name='oficios_prestamo_bien_unico'),
        ),
        migrations.AddConstraint(
            model_name='prestamobien',
            constraint=models.UniqueConstraint(condition=models.Q(('abierto', True)), fields=('bien',), name='oficios_bien_en_un_solo_prestamo_abierto'),
        ),
    ]
