# Generated by Django 6.0.6 on 2026-09-25 05:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def rellenar_bitacora(apps, schema_editor):
    """Los bienes y préstamos anteriores a la bitácora reciben sus entradas de alta, préstamo y devolución."""
    Bien = apps.get_model("seguimientos_oficios", "Bien")
    Historial = apps.get_model("seguimientos_oficios", "HistorialBien")
    PrestamoBien = apps.get_model("seguimientos_oficios", "PrestamoBien")
    etiqueta = "Anterior a la bitácora"

    def poner(bien, accion, fecha, datos):
        entrada = Historial.objects.create(bien=bien, accion=accion, usuario_nombre=etiqueta, datos=datos)
        Historial.objects.filter(pk=entrada.pk).update(created_at=fecha)

    for bien in Bien.objects.all():
        poner(bien, "alta", bien.created_at, {"nombre": bien.nombre, "identificador": bien.identificador})
    for renglon in PrestamoBien.objects.select_related("bien", "prestamo", "prestamo__documento").order_by("prestamo__created_at"):
        prestamo, documento = renglon.prestamo, renglon.prestamo.documento
        datos = {"folio": documento.folio, "recibe": documento.contraparte, "fecha_limite": prestamo.fecha_limite.isoformat()}
        poner(renglon.bien, "prestamo", prestamo.created_at, datos)
        if prestamo.fecha_devolucion:
            poner(renglon.bien, "devolucion", prestamo.updated_at, {**datos, "devolucion": prestamo.fecha_devolucion.isoformat()})
        elif documento.estado == "cancelado":
            poner(renglon.bien, "liberado", documento.updated_at, datos)


class Migration(migrations.Migration):

    dependencies = [
        ('seguimientos_oficios', '0023_bienes_y_prestamos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialBien',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accion', models.CharField(choices=[('alta', 'Alta'), ('editado', 'Datos editados'), ('estado', 'Cambio de estado'), ('prestamo', 'Prestado'), ('devolucion', 'Devuelto'), ('liberado', 'Vale cancelado')], max_length=12)),
                ('usuario_nombre', models.CharField(blank=True, max_length=200)),
                ('datos', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial', to='seguimientos_oficios.bien')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'oficios_historial_bien',
                'ordering': ['created_at'],
            },
        ),
        migrations.RunPython(rellenar_bitacora, migrations.RunPython.noop),
    ]
