# Generated by Django 6.0.6 on 2026-09-25 06:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimientos_oficios', '0024_bitacora_de_bienes'),
    ]

    operations = [
        migrations.AddField(
            model_name='bien',
            name='marca_modelo',
            field=models.CharField(blank=True, max_length=150, verbose_name='Marca y modelo'),
        ),
        migrations.AddField(
            model_name='direccion',
            name='soporte_habilitado',
            field=models.BooleanField(default=False, help_text='Activo: la dirección emite diagnósticos y dictámenes de alta y baja (área Soporte técnico).', verbose_name='Soporte técnico'),
        ),
        migrations.AlterField(
            model_name='historialbien',
            name='accion',
            field=models.CharField(choices=[('alta', 'Alta'), ('editado', 'Datos editados'), ('estado', 'Cambio de estado'), ('prestamo', 'Prestado'), ('devolucion', 'Devuelto'), ('liberado', 'Vale cancelado'), ('diagnostico', 'Diagnóstico técnico'), ('dictamen', 'Dictamen de baja')], max_length=12),
        ),
        migrations.AlterField(
            model_name='nomenclatura',
            name='plantilla',
            field=models.CharField(default='{n:03d}/{anio}', help_text='Ej. IN-{n:03d}/{anio} da IN-001/2026. Tokens: {n}, {n:03d}, {anio} (2026) y {anio2} (26).', max_length=60, verbose_name='Plantilla'),
        ),
        migrations.CreateModel(
            name='Dictamen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Eliminado')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('ticket', models.CharField(blank=True, max_length=60, verbose_name='Ticket de la mesa de ayuda')),
                ('elaboro_nombre', models.CharField(max_length=200)),
                ('elaboro_cargo', models.CharField(blank=True, max_length=200)),
                ('autoriza_nombre', models.CharField(blank=True, max_length=200)),
                ('autoriza_cargo', models.CharField(blank=True, max_length=200)),
                ('datos', models.JSONField(default=dict, verbose_name='Contenido')),
                ('documento', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='dictamen', to='seguimientos_oficios.documento')),
            ],
            options={
                'db_table': 'oficios_dictamen',
            },
        ),
        migrations.CreateModel(
            name='DictamenBien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('equipo', models.CharField(max_length=150)),
                ('marca_modelo', models.CharField(blank=True, max_length=150)),
                ('serie', models.CharField(blank=True, max_length=120)),
                ('folio_inventario', models.CharField(blank=True, max_length=60)),
                ('departamento', models.CharField(blank=True, max_length=150)),
                ('bien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dictamenes', to='seguimientos_oficios.bien')),
                ('dictamen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipos', to='seguimientos_oficios.dictamen')),
            ],
            options={
                'db_table': 'oficios_dictamen_bien',
                'ordering': ['orden'],
            },
        ),
    ]
