# Generated by Django 6.0.6 on 2026-09-25 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimientos_oficios', '0026_categorias_de_bienes'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictamenbien',
            name='info_tecnica',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dictamenbien',
            name='tipo',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='documento',
            name='clase',
            field=models.CharField(choices=[('oficio', 'Oficio'), ('vale_prestamo', 'Vale de préstamo'), ('diagnostico_tecnico', 'Diagnóstico técnico'), ('dictamen_alta', 'Dictamen de alta'), ('dictamen_baja', 'Dictamen de baja'), ('resguardo', 'Resguardo de equipos'), ('comunicado', 'Comunicado'), ('otro', 'Otro')], default='oficio', max_length=25, verbose_name='Clase de documento'),
        ),
        migrations.AlterField(
            model_name='historialbien',
            name='accion',
            field=models.CharField(choices=[('alta', 'Alta'), ('editado', 'Datos editados'), ('estado', 'Cambio de estado'), ('prestamo', 'Prestado'), ('devolucion', 'Devuelto'), ('liberado', 'Vale cancelado'), ('diagnostico', 'Diagnóstico técnico'), ('dictamen', 'Dictamen de baja'), ('resguardo', 'Resguardo')], max_length=12),
        ),
        migrations.AlterField(
            model_name='nomenclatura',
            name='clase',
            field=models.CharField(choices=[('oficio', 'Oficio'), ('vale_prestamo', 'Vale de préstamo'), ('diagnostico_tecnico', 'Diagnóstico técnico'), ('dictamen_alta', 'Dictamen de alta'), ('dictamen_baja', 'Dictamen de baja'), ('resguardo', 'Resguardo de equipos'), ('comunicado', 'Comunicado'), ('otro', 'Otro')], max_length=25, verbose_name='Clase de documento'),
        ),
    ]
